#!/usr/bin/env bash

alias coab='composer about'                # Shows the short information about Composer.
alias coar='composer archive'              # Creates an archive of this composer package.
alias cob='composer browse'                # Opens the package's repository URL or homepage in your browser.
alias cocc='composer clear-cache'          # Clears composer's internal package cache.
alias cocpr='composer check-platform-reqs' # Check that platform requirements are satisfied.
alias cocfg='composer config'              # Sets config options.
alias cocp='composer create-project'       # Creates new project from a package into given directory.
alias codp='composer depends'              # Shows which packages cause the given package to be installed.
alias codiag='composer diagnose'           # Diagnoses the system to identify common errors.
alias codmp='composer dump-autoload'       # Dumps the autoloader.
alias coex='composer exec'                 # Executes a vendored binary/script.
alias cof='composer fund'                  # Discover how to help fund the maintenance of your dependencies.
alias coglob='composer global'             # Allows running commands in the global composer dir ($COMPOSER_HOME).
alias coh='composer help'                  # Displays help for a command
alias cohome='composer home'               #  Opens the package's repository URL or homepage in your browser.
alias coi='composer install'               # Installs the project dependencies from the composer.lock file if present, or falls back on the composer.json.
alias coinf='composer info'                # Shows information about packages.
alias coini='composer init'                # Creates a basic composer.json file in current directory.
alias coli='composer licenses'             # Shows information about licenses of dependencies.
alias colis='composer list'                # Lists commands
alias coout='composer outdated'            # Shows a list of installed packages that have updates available, including their latest version.
alias cop='composer prohibits'             # Shows which packages prevent the given package from being installed.
alias corem='composer remove'              # Removes a package from the require or require-dev.
alias coreq='composer require'             # Adds required packages to your composer.json and installs them.
alias coreqd='composer require --dev'      # Adds required dev packages to your composer.json and installs them.
alias cors='composer run-script'           # Runs the scripts defined in composer.json.
alias cos='composer search'                # Searches for packages.
alias cosu='composer self-update'          # Updates composer.phar to the latest version.
alias coshow='composer show'               # Shows information about packages.
alias costat='composer status'             # Shows a list of locally modified packages, for packages installed from source.
alias cosugg='composer suggest'            # Shows package suggestions.
alias coup='composer update'               # Upgrades your dependencies to the latest version according to composer.json, and updates the composer.lock file.
alias coval='composer validate'            # Validates a composer.json and composer.lock.
alias cowhy='composer why'                 # Shows which packages cause the given package to be installed.
alias cowhyn='composer why-not'            # Shows which packages prevent the given package from being installed.
alias comgu='composer global update'       # Update global packages
