name: CI
on:
  - pull_request
  - push
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ macos-latest ]
    name: Setup installation & theme tests on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        id: extract_branch

      # print branch name
      - name: Get branch name
        run: echo 'The branch name is' $BRANCH_NAME

      - name: install with one-liner bootstrap and relaunch
        run: |
          S_UPGRADE=0 /bin/bash -c "$(curl -fsS https://raw.githubusercontent.com/rayyh/setup/${BRANCH_NAME}/bootstrap.sh)" | tee ~/.bootstrap.log
