name: Test
on:
  - pull_request
  - push
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
    name: Setup installation tests on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installation
        run: ./install.sh
        shell: bash
